### ISSUE TITLE
Suspected hash trie off-by-one

### ISSUE THREAD

**Issue by wotbrew** [xtdb/crux#2671] opened 2023-08-07 13:05 UTC
Repro:

```clojure
(with-open [node (node/start-node {})]
  (dotimes [x 10000]
    (xt/submit-tx node [[:put :foo {:xt/id 0, :n x}]]))

  (xt/q node '{:find [n] :where [($ :foo [{:xt/id 0, :n n}])]}))
```

Results in a bunch of indexing/subscriber related errors, ingester stops.

```
clojure.lang.ExceptionInfo: Ingestion stopped: index: 65024, length: 1 (expected: range(0, 65024)) {}
	at xtdb.await$__GT_ingester_ex.invokeStatic(await.clj:17)
java.lang.IndexOutOfBoundsException: index: 65024, length: 1 (expected: range(0, 65024))
	at org.apache.arrow.memory.ArrowBuf.checkIndexD(ArrowBuf.java:319)
	at org.apache.arrow.memory.ArrowBuf.chk(ArrowBuf.java:306)
	at org.apache.arrow.memory.ArrowBuf.getByte(ArrowBuf.java:508)
	at xtdb.trie.HashTrie.bucketFor(HashTrie.java:42)
	at xtdb.trie.LiveHashTrie.bucketFor(LiveHashTrie.java:62)
	at xtdb.trie.LiveHashTrie$Branch.add(LiveHashTrie.java:88)
```

**Comment by mbutlerw** [comment] 2023-08-08 11:16
Closing as duplicate of https://github.com/xtdb/xtdb/issues/2630

**Closed as not planned by mbutlerw** 2023-08-08 11:16 UTC
Labels: duplicate
