### ISSUE TITLE
Flaky Tests / Race Condition

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/crux#2755] opened 2023-09-04 17:22 UTC
I think I've seen the former before, creating an issue to help track.

can-ingest-ts-devices-mini-into-multiple-nodes
```
org.opentest4j.AssertionFailedError: FAIL in  (can-ingest-ts-devices-mini-into-multiple-nodes) (indexer_test.clj:441)
expected:  (= 11 (count (filter (fn* [p1__41975#] (re-matches #"chunk-metadata/\p{XDigit}+\.transit.json" p1__41975#)) objs)))
  actual:  (not (= 11 10))

	at dev.clojurephant.jovial.engine.clojure_test$eval914$fn__915.invoke(clojure_test.clj:75)
	at app//clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at app//clojure.test$do_report.invokeStatic(test.clj:357)
	at app//clojure.test$do_report.invoke(test.clj:351)
	at app//xtdb.indexer_test$fn__41981$fn__42016.invoke(indexer_test.clj:441)
	at app//xtdb.indexer_test$fn__41981.invokeStatic(indexer_test.clj:441)
	at app//xtdb.indexer_test$fn__41981.invoke(indexer_test.clj:410)
	at dev.clojurephant.jovial.engine.clojure_test$eval886$fn__889.invoke(clojure_test.clj:34)
	at dev.clojurephant.jovial.engine.clojure_test$eval844$fn__856$G__835__861.invoke(clojure_test.clj:16)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899$fn__900.invoke(clojure_test.clj:53)
	at app//clojure.test$default_fixture.invokeStatic(test.clj:687)
	at app//clojure.test$default_fixture.invoke(test.clj:683)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899.invoke(clojure_test.clj:51)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invokeStatic(clojure_test.clj:50)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invoke(clojure_test.clj:46)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899$fn__900.invoke(clojure_test.clj:55)
	at app//xtdb.test_util$with_allocator$fn__24063.invoke(test_util.clj:45)
	at app//xtdb.test_util$with_allocator.invokeStatic(test_util.clj:43)
	at app//xtdb.test_util$with_allocator.invoke(test_util.clj:42)
	at app//clojure.test$compose_fixtures$fn__9878$fn__9879.invoke(test.clj:694)
	at app//clojure.test$default_fixture.invokeStatic(test.clj:687)
	at app//clojure.test$default_fixture.invoke(test.clj:683)
	at app//clojure.test$compose_fixtures$fn__9878.invoke(test.clj:694)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899.invoke(clojure_test.clj:51)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invokeStatic(clojure_test.clj:50)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invoke(clojure_test.clj:46)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899$fn__900.invoke(clojure_test.clj:55)
	at dev.clojurephant.jovial.engine.clojure_test$eval872$fn__873$fn__874.invoke(clojure_test.clj:22)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899.invoke(clojure_test.clj:51)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invokeStatic(clojure_test.clj:50)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invoke(clojure_test.clj:46)
	at dev.clojurephant.jovial.engine.clojure_test.Engine.execute(clojure_test.clj:113)
	at dev.clojurephant.jovial.engine$eval661$fn__688$G__653__691.invoke(engine.clj:23)
	at dev.clojurephant.jovial.engine$eval661$fn__688$G__652__695.invoke(engine.clj:23)
	at app//clojure.lang.AFn.applyToHelper(AFn.java:156)
	at app//clojure.lang.AFn.applyTo(AFn.java:144)
	at app//clojure.lang.Var.applyTo(Var.java:707)
	at app//clojure.core$apply.invokeStatic(core.clj:667)
	at app//clojure.core$apply.invoke(core.clj:662)
	at app//clojure.lang.Var.invoke(Var.java:390)
	at app//dev.clojurephant.jovial.util.SimpleClojure.invoke(SimpleClojure.java:21)
	at app//dev.clojurephant.jovial.BaseClojureEngine.execute(BaseClojureEngine.java:32)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
	Suppressed: org.opentest4j.AssertionFailedError: FAIL in  (can-ingest-ts-devices-mini-into-multiple-nodes) (indexer_test.clj:443)
expected:  (= 11 (count (filter (fn* [p1__41977#] (re-matches #"tables/device_readings/log-leaves/leaf-l\p{XDigit}+-cf\p{XDigit}+-ct\p{XDigit}+\.arrow" p1__41977#)) objs)))
  actual:  (not (= 11 10))

		at dev.clojurephant.jovial.engine.clojure_test$eval914$fn__915.invoke(clojure_test.clj:75)
		at app//clojure.lang.MultiFn.invoke(MultiFn.java:229)
		at app//clojure.test$do_report.invokeStatic(test.clj:357)
		at app//clojure.test$do_report.invoke(test.clj:351)
		at app//xtdb.indexer_test$fn__41981$fn__42028.invoke(indexer_test.clj:443)
		at app//xtdb.indexer_test$fn__41981.invokeStatic(indexer_test.clj:443)
		... 67 more
	Suppressed: org.opentest4j.AssertionFailedError: FAIL in  (can-ingest-ts-devices-mini-into-multiple-nodes) (indexer_test.clj:444)
expected:  (= 11 (count (filter (fn* [p1__41978#] (re-matches #"tables/device_readings/log-tries/trie-l\p{XDigit}+-cf\p{XDigit}+-ct\p{XDigit}+\.arrow" p1__41978#)) objs)))
  actual:  (not (= 11 10))

		at dev.clojurephant.jovial.engine.clojure_test$eval914$fn__915.invoke(clojure_test.clj:75)
		at app//clojure.lang.MultiFn.invoke(MultiFn.java:229)
		at app//clojure.test$do_report.invokeStatic(test.clj:357)
		at app//clojure.test$do_report.invoke(test.clj:351)
		at app//xtdb.indexer_test$fn__41981$fn__42034.invoke(indexer_test.clj:444)
		at app//xtdb.indexer_test$fn__41981.invokeStatic(indexer_test.clj:444)
		... 67 more
	Suppressed: org.opentest4j.AssertionFailedError: FAIL in  (can-ingest-ts-devices-mini-into-multiple-nodes) (indexer_test.clj:445)
expected:  (= 11 (count (filter (fn* [p1__41979#] (re-matches #"tables/xt\$txs/log-leaves/leaf-l\p{XDigit}+-cf\p{XDigit}+-ct\p{XDigit}+\.arrow" p1__41979#)) objs)))
  actual:  (not (= 11 10))

		at dev.clojurephant.jovial.engine.clojure_test$eval914$fn__915.invoke(clojure_test.clj:75)
		at app//clojure.lang.MultiFn.invoke(MultiFn.java:229)
		at app//clojure.test$do_report.invokeStatic(test.clj:357)
		at app//clojure.test$do_report.invoke(test.clj:351)
		at app//xtdb.indexer_test$fn__41981$fn__42040.invoke(indexer_test.clj:445)
		at app//xtdb.indexer_test$fn__41981.invokeStatic(indexer_test.clj:445)
		... 67 more
	Suppressed: org.opentest4j.AssertionFailedError: FAIL in  (can-ingest-ts-devices-mini-into-multiple-nodes) (indexer_test.clj:446)
expected:  (= 11 (count (filter (fn* [p1__41980#] (re-matches #"tables/xt\$txs/log-tries/trie-l\p{XDigit}+-cf\p{XDigit}+-ct\p{XDigit}+\.arrow" p1__41980#)) objs)))
  actual:  (not (= 11 10))

		at dev.clojurephant.jovial.engine.clojure_test$eval914$fn__915.invoke(clojure_test.clj:75)
		at app//clojure.lang.MultiFn.invoke(MultiFn.java:229)
		at app//clojure.test$do_report.invokeStatic(test.clj:357)
		at app//clojure.test$do_report.invoke(test.clj:351)
		at app//xtdb.indexer_test$fn__41981$fn__42046.invoke(indexer_test.clj:446)
		at app//xtdb.indexer_test$fn__41981.invokeStatic(indexer_test.clj:446)
		... 67 more

```

can-write-put-fns

```org.opentest4j.AssertionFailedError: FAIL in  (can-write-put-fns) (tx_producer_test.clj:22)
expected:  (= (json/parse-string (slurp file)) (json/parse-string actual))
  actual:  (not (= {"schema" {"fields" [{"name" "tx-ops", "nullable" false, "type" {"name" "list"}, "children" [{"name" "$data$", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" [0 1 2 3 4 5]}, "children" [{"name" "sql", "nullable" false, "type" {"name" "struct"}, "children" [{"name" "query", "nullable" false, "type" {"name" "utf8"}, "children" []} {"name" "params", "nullable" true, "type" {"name" "binary"}, "children" []}]} {"name" "put", "nullable" false, "type" {"name" "struct"}, "children" [{"name" "document", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" [{"name" "xt$tx_fns", "nullable" false, "type" {"name" "struct"}, "children" [{"name" "xt$id", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" [{"name" "keyword", "nullable" false, "type" {"name" "KeywordType"}, "children" [], "metadata" [{"value" "xt/clj-keyword", "key" "ARROW:extension:name"} {"value" "", "key" "ARROW:extension:metadata"}]}]} {"name" "xt$fn", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" [{"name" "clj-form", "nullable" false, "type" {"name" "ClojureFormType"}, "children" [], "metadata" [{"value" "xt/clj-form", "key" "ARROW:extension:name"} {"value" "", "key" "ARROW:extension:metadata"}]}]}]}]} {"name" "xt$valid_from", "nullable" true, "type" {"name" "timestamp", "unit" "MICROSECOND", "timezone" "UTC"}, "children" []} {"name" "xt$valid_to", "nullable" true, "type" {"name" "timestamp", "unit" "MICROSECOND", "timezone" "UTC"}, "children" []}]} {"name" "delete", "nullable" false, "type" {"name" "struct"}, "children" [{"name" "table", "nullable" false, "type" {"name" "utf8"}, "children" []} {"name" "xt$id", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" []} {"name" "xt$valid_from", "nullable" true, "type" {"name" "timestamp", "unit" "MICROSECOND", "timezone" "UTC"}, "children" []} {"name" "xt$valid_to", "nullable" true, "type" {"name" "timestamp", "unit" "MICROSECOND", "timezone" "UTC"}, "children" []}]} {"name" "evict", "nullable" false, "type" {"name" "struct"}, "children" [{"name" "_table", "nullable" true, "type" {"name" "utf8"}, "children" []} {"name" "xt$id", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" []}]} {"name" "call", "nullable" false, "type" {"name" "struct"}, "children" [{"name" "fn-id", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" []} {"name" "args", "nullable" false, "type" {"name" "list"}, "children" [{"name" "$data$", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" []}]}]} {"name" "abort", "nullable" true, "type" {"name" "null"}, "children" []}]}]} {"name" "system-time", "nullable" true, "type" {"name" "timestamp", "unit" "MICROSECOND", "timezone" "UTC"}, "children" []} {"name" "default-tz", "nullable" false, "type" {"name" "utf8"}, "children" []} {"name" "all-application-time?", "nullable" false, "type" {"name" "bool"}, "children" []}]}, "batches" [{"count" 1, "columns" [{"name" "tx-ops", "count" 1, "VALIDITY" [1], "OFFSET" [0 2], "children" [{"name" "$data$", "count" 2, "TYPE_ID" [1 1], "OFFSET" [0 1], "children" [{"name" "sql", "count" 0, "VALIDITY" [], "children" [{"name" "query", "count" 0, "VALIDITY" [], "OFFSET" [0], "DATA" []} {"name" "params", "count" 0, "VALIDITY" [], "OFFSET" [0], "DATA" []}]} {"name" "put", "count" 2, "VALIDITY" [1 1], "children" [{"name" "document", "count" 2, "TYPE_ID" [0 0], "OFFSET" [0 1], "children" [{"name" "xt$tx_fns", "count" 2, "VALIDITY" [1 1], "children" [{"name" "xt$id", "count" 2, "TYPE_ID" [0 0], "OFFSET" [0 1], "children" [{"name" "keyword", "count" 2, "VALIDITY" [1 1], "OFFSET" [0 3 6], "DATA" ["foo" "bar"]}]} {"name" "xt$fn", "count" 2, "TYPE_ID" [0 0], "OFFSET" [0 1], "children" [{"name" "clj-form", "count" 2, "VALIDITY" [1 1], "OFFSET" [0 35 70], "DATA" ["(fn [id] [[:put :foo {:xt/id id}]])" "(fn [id] [[:put :bar {:xt/id id}]])"]}]}]}]} {"name" "xt$valid_from", "count" 2, "VALIDITY" [0 1], "DATA" [0 1577836800000000]} {"name" "xt$valid_to", "count" 2, "VALIDITY" [0 0], "DATA" [0 0]}]} {"name" "delete", "count" 0, "VALIDITY" [], "children" [{"name" "table", "count" 0, "VALIDITY" [], "OFFSET" [0], "DATA" []} {"name" "xt$id", "count" 0, "TYPE_ID" [], "OFFSET" []} {"name" "xt$valid_from", "count" 0, "VALIDITY" [], "DATA" []} {"name" "xt$valid_to", "count" 0, "VALIDITY" [], "DATA" []}]} {"name" "evict", "count" 0, "VALIDITY" [], "children" [{"name" "_table", "count" 0, "VALIDITY" [], "OFFSET" [0], "DATA" []} {"name" "xt$id", "count" 0, "TYPE_ID" [], "OFFSET" []}]} {"name" "call", "count" 0, "VALIDITY" [], "children" [{"name" "fn-id", "count" 0, "TYPE_ID" [], "OFFSET" []} {"name" "args", "count" 0, "VALIDITY" [], "OFFSET" [0], "children" [{"name" "$data$", "count" 0, "TYPE_ID" [], "OFFSET" []}]}]} {"name" "abort", "count" 0}]}]} {"name" "system-time", "count" 1, "VALIDITY" [0], "DATA" [0]} {"name" "default-tz", "count" 1, "VALIDITY" [1], "OFFSET" [0 0], "DATA" [""]} {"name" "all-application-time?", "count" 1, "VALIDITY" [1], "DATA" [0]}]}]} {"schema" {"fields" [{"name" "tx-ops", "nullable" false, "type" {"name" "list"}, "children" [{"name" "$data$", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" [0 1 2 3 4 5]}, "children" [{"name" "sql", "nullable" false, "type" {"name" "struct"}, "children" [{"name" "query", "nullable" false, "type" {"name" "utf8"}, "children" []} {"name" "params", "nullable" true, "type" {"name" "binary"}, "children" []}]} {"name" "put", "nullable" false, "type" {"name" "struct"}, "children" [{"name" "document", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" [{"name" "xt$tx_fns", "nullable" false, "type" {"name" "struct"}, "children" [{"name" "xt$fn", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" [{"name" "clj-form", "nullable" false, "type" {"name" "ClojureFormType"}, "children" [], "metadata" [{"value" "xt/clj-form", "key" "ARROW:extension:name"} {"value" "", "key" "ARROW:extension:metadata"}]}]} {"name" "xt$id", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" [{"name" "keyword", "nullable" false, "type" {"name" "KeywordType"}, "children" [], "metadata" [{"value" "xt/clj-keyword", "key" "ARROW:extension:name"} {"value" "", "key" "ARROW:extension:metadata"}]}]}]}]} {"name" "xt$valid_from", "nullable" true, "type" {"name" "timestamp", "unit" "MICROSECOND", "timezone" "UTC"}, "children" []} {"name" "xt$valid_to", "nullable" true, "type" {"name" "timestamp", "unit" "MICROSECOND", "timezone" "UTC"}, "children" []}]} {"name" "delete", "nullable" false, "type" {"name" "struct"}, "children" [{"name" "table", "nullable" false, "type" {"name" "utf8"}, "children" []} {"name" "xt$id", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" []} {"name" "xt$valid_from", "nullable" true, "type" {"name" "timestamp", "unit" "MICROSECOND", "timezone" "UTC"}, "children" []} {"name" "xt$valid_to", "nullable" true, "type" {"name" "timestamp", "unit" "MICROSECOND", "timezone" "UTC"}, "children" []}]} {"name" "evict", "nullable" false, "type" {"name" "struct"}, "children" [{"name" "_table", "nullable" true, "type" {"name" "utf8"}, "children" []} {"name" "xt$id", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" []}]} {"name" "call", "nullable" false, "type" {"name" "struct"}, "children" [{"name" "fn-id", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" []} {"name" "args", "nullable" false, "type" {"name" "list"}, "children" [{"name" "$data$", "nullable" false, "type" {"name" "union", "mode" "Dense", "typeIds" []}, "children" []}]}]} {"name" "abort", "nullable" true, "type" {"name" "null"}, "children" []}]}]} {"name" "system-time", "nullable" true, "type" {"name" "timestamp", "unit" "MICROSECOND", "timezone" "UTC"}, "children" []} {"name" "default-tz", "nullable" false, "type" {"name" "utf8"}, "children" []} {"name" "all-application-time?", "nullable" false, "type" {"name" "bool"}, "children" []}]}, "batches" [{"count" 1, "columns" [{"name" "tx-ops", "count" 1, "VALIDITY" [1], "OFFSET" [0 2], "children" [{"name" "$data$", "count" 2, "TYPE_ID" [1 1], "OFFSET" [0 1], "children" [{"name" "sql", "count" 0, "VALIDITY" [], "children" [{"name" "query", "count" 0, "VALIDITY" [], "OFFSET" [0], "DATA" []} {"name" "params", "count" 0, "VALIDITY" [], "OFFSET" [0], "DATA" []}]} {"name" "put", "count" 2, "VALIDITY" [1 1], "children" [{"name" "document", "count" 2, "TYPE_ID" [0 0], "OFFSET" [0 1], "children" [{"name" "xt$tx_fns", "count" 2, "VALIDITY" [1 1], "children" [{"name" "xt$fn", "count" 2, "TYPE_ID" [0 0], "OFFSET" [0 1], "children" [{"name" "clj-form", "count" 2, "VALIDITY" [1 1], "OFFSET" [0 35 70], "DATA" ["(fn [id] [[:put :foo {:xt/id id}]])" "(fn [id] [[:put :bar {:xt/id id}]])"]}]} {"name" "xt$id", "count" 2, "TYPE_ID" [0 0], "OFFSET" [0 1], "children" [{"name" "keyword", "count" 2, "VALIDITY" [1 1], "OFFSET" [0 3 6], "DATA" ["foo" "bar"]}]}]}]} {"name" "xt$valid_from", "count" 2, "VALIDITY" [0 1], "DATA" [0 1577836800000000]} {"name" "xt$valid_to", "count" 2, "VALIDITY" [0 0], "DATA" [0 0]}]} {"name" "delete", "count" 0, "VALIDITY" [], "children" [{"name" "table", "count" 0, "VALIDITY" [], "OFFSET" [0], "DATA" []} {"name" "xt$id", "count" 0, "TYPE_ID" [], "OFFSET" []} {"name" "xt$valid_from", "count" 0, "VALIDITY" [], "DATA" []} {"name" "xt$valid_to", "count" 0, "VALIDITY" [], "DATA" []}]} {"name" "evict", "count" 0, "VALIDITY" [], "children" [{"name" "_table", "count" 0, "VALIDITY" [], "OFFSET" [0], "DATA" []} {"name" "xt$id", "count" 0, "TYPE_ID" [], "OFFSET" []}]} {"name" "call", "count" 0, "VALIDITY" [], "children" [{"name" "fn-id", "count" 0, "TYPE_ID" [], "OFFSET" []} {"name" "args", "count" 0, "VALIDITY" [], "OFFSET" [0], "children" [{"name" "$data$", "count" 0, "TYPE_ID" [], "OFFSET" []}]}]} {"name" "abort", "count" 0}]}]} {"name" "system-time", "count" 1, "VALIDITY" [0], "DATA" [0]} {"name" "default-tz", "count" 1, "VALIDITY" [1], "OFFSET" [0 0], "DATA" [""]} {"name" "all-application-time?", "count" 1, "VALIDITY" [1], "DATA" [0]}]}]}))

	at dev.clojurephant.jovial.engine.clojure_test$eval914$fn__915.invoke(clojure_test.clj:75)
	at app//clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at app//clojure.test$do_report.invokeStatic(test.clj:357)
	at app//clojure.test$do_report.invoke(test.clj:351)
	at app//xtdb.tx_producer_test$test_serialize_tx_ops.invokeStatic(tx_producer_test.clj:22)
	at app//xtdb.tx_producer_test$test_serialize_tx_ops.invoke(tx_producer_test.clj:12)
	at app//xtdb.tx_producer_test$test_serialize_tx_ops.invokeStatic(tx_producer_test.clj:13)
	at app//xtdb.tx_producer_test$test_serialize_tx_ops.invoke(tx_producer_test.clj:12)
	at app//xtdb.tx_producer_test$fn__41604.invokeStatic(tx_producer_test.clj:73)
	at app//xtdb.tx_producer_test$fn__41604.invoke(tx_producer_test.clj:72)
	at dev.clojurephant.jovial.engine.clojure_test$eval886$fn__889.invoke(clojure_test.clj:34)
	at dev.clojurephant.jovial.engine.clojure_test$eval844$fn__856$G__835__861.invoke(clojure_test.clj:16)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899$fn__900.invoke(clojure_test.clj:53)
	at app//xtdb.test_util$with_allocator$fn__24063.invoke(test_util.clj:45)
	at app//xtdb.test_util$with_allocator.invokeStatic(test_util.clj:43)
	at app//xtdb.test_util$with_allocator.invoke(test_util.clj:42)
	at app//clojure.test$compose_fixtures$fn__9878$fn__9879.invoke(test.clj:694)
	at app//clojure.test$default_fixture.invokeStatic(test.clj:687)
	at app//clojure.test$default_fixture.invoke(test.clj:683)
	at app//clojure.test$compose_fixtures$fn__9878.invoke(test.clj:694)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899.invoke(clojure_test.clj:51)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invokeStatic(clojure_test.clj:50)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invoke(clojure_test.clj:46)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899$fn__900.invoke(clojure_test.clj:55)
	at app//clojure.test$default_fixture.invokeStatic(test.clj:687)
	at app//clojure.test$default_fixture.invoke(test.clj:683)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899.invoke(clojure_test.clj:51)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invokeStatic(clojure_test.clj:50)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invoke(clojure_test.clj:46)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899$fn__900.invoke(clojure_test.clj:55)
	at dev.clojurephant.jovial.engine.clojure_test$eval872$fn__873$fn__874.invoke(clojure_test.clj:22)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899.invoke(clojure_test.clj:51)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invokeStatic(clojure_test.clj:50)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invoke(clojure_test.clj:46)
	at dev.clojurephant.jovial.engine.clojure_test.Engine.execute(clojure_test.clj:113)
	at dev.clojurephant.jovial.engine$eval661$fn__688$G__653__691.invoke(engine.clj:23)
	at dev.clojurephant.jovial.engine$eval661$fn__688$G__652__695.invoke(engine.clj:23)
	at app//clojure.lang.AFn.applyToHelper(AFn.java:156)
	at app//clojure.lang.AFn.applyTo(AFn.java:144)
	at app//clojure.lang.Var.applyTo(Var.java:707)
	at app//clojure.core$apply.invokeStatic(core.clj:667)
	at app//clojure.core$apply.invoke(core.clj:662)
	at app//clojure.lang.Var.invoke(Var.java:390)
	at app//dev.clojurephant.jovial.util.SimpleClojure.invoke(SimpleClojure.java:21)
	at app//dev.clojurephant.jovial.BaseClojureEngine.execute(BaseClojureEngine.java:32)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
	```

**Comment by mbutlerw** [comment] 2023-09-07 17:05
Happened again today.

**Comment by danmason** [comment] 2023-10-30 10:09
Have seen also seen a [**few failures now on CI**](https://github.com/xtdb/xtdb/actions/runs/6691047383/job/18177521033?pr=2861) against this.

One assertion failied from the particular run:
```clojure
org.opentest4j.AssertionFailedError: FAIL in  (can-ingest-ts-devices-mini-into-multiple-nodes) (indexer_test.clj:433)
expected:  (= 11 (count (filter (fn* [p1__44821#] (re-matches #"chunk-metadata/\p{XDigit}+\.transit.json" p1__44821#)) objs)))
  actual:  (not (= 11 10))
```

**Comment by jarohen** [comment] 2023-11-01 10:57
duplicate of #2690

**Closed as not planned by jarohen** 2023-11-01 10:57 UTC
Labels: duplicate
