### ISSUE TITLE
Deletion fails with `copyFromSafe` error

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#2998] opened 2023-11-29 10:50 UTC
The following:
```clojure
(t/deftest test-issue
  (xt/submit-tx tu/*node* [(xt/put :posts {:xt/id 1 :author-id "james"})
                           (xt/put :comments {:xt/id :test :post-id 1})])

  (xt/submit-tx tu/*node*
                [(-> (xt/xtql-op '(delete :comments [{:post-id pid}]
                                          (from :posts [{:xt/id pid, :author-id $author}])))
                     (xt/with-op-args {:author "james"}))])

  (t/is (xt/q tu/*node* '(from :posts []))))
```

leads to this ingestion error on the `delete`:

```
        Preconditions.java:  122  org.apache.arrow.util.Preconditions/checkArgument
 BaseFixedWidthVector.java:  892  org.apache.arrow.vector.BaseFixedWidthVector/copyFromSafe
                writer.clj:   66  xtdb.vector.writer/scalar-copier/reify
                writer.clj: 1019  xtdb.vector.writer//reify
                   map.clj:  225  xtdb.expression.map//reify/add
                   map.clj:   -1  xtdb.expression.map//reify/add
                   map.clj:  231  xtdb.expression.map//reify/reify
                  join.clj:  172  xtdb.operator.join/build-phase/reify
```

**Comment by Akeboshiwind** [comment] 2023-11-29 10:53
Also interesting to note if you use SQL to delete instead then you don't get this error:
```clojure
(xt/submit-tx tu/*node*
  [(-> (xt/sql-op "DELETE FROM comments
                   WHERE comments.post_id IN (SELECT posts.xt$id FROM posts WHERE posts.author_id = ?)")
       (xt/with-op-args ["james"]))])
```

**Comment by jarohen** [comment] 2023-12-05 11:50
dupe of #3016

**Closed as not planned by jarohen** 2023-12-05 11:50 UTC
Labels: duplicate, xtql
