### ISSUE TITLE
pgwire should return more detailed query errors than `Illegal argument: 'malformed-query'`

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3570] opened 2024-08-06 11:42 UTC
```
jdt=> SELECT 2 AS b FROM docs GROUP BY b;
ERROR:  Illegal argument: 'malformed-query'
```

```
11:38:54 | WARN  xtdb.sql.plan | Table not found: docs
11:38:54 | WARN  xtdb.sql.plan | Column not found: b
11:38:54 | ERROR xtdb.pgwire | #xt/illegal-arg [:malformed-query Illegal argument: 'malformed-query' {:plan [:project [{b 2}] [:group-by [nil] [:rename docs.1 [:scan {:table docs} []]]]], :explain {:clojure.spec.alpha/problems ({:path [:project :relation :group-by :columns :group-by], :pred clojure.core/symbol?, :val nil, :via [:xtdb.logical-plan/logical-plan :xtdb.logical-plan/ra-expression :xtdb.logical-plan/ra-expression :xtdb.logical-plan/column], :in [2 1 0]} {:path [:project :relation :group-by :columns :aggregate], :pred clojure.core/map?, :val nil, :via [:xtdb.logical-plan/logical-plan :xtdb.logical-plan/ra-expression :xtdb.logical-plan/ra-expression :xtdb.operator.group-by/aggregate], :in [2 1 0]}), :clojure.spec.alpha/spec :xtdb.logical-plan/logical-plan, :clojure.spec.alpha/value [:project [{b 2}] [:group-by [nil] [:rename docs.1 [:scan {:table docs} []]]]]}}]
```

**Comment by jarohen** [comment] 2024-08-06 11:45
thanks @refset - dupe of #3461 I think?

**Closed as not planned by jarohen** 2024-08-06 11:45 UTC
Labels: duplicate, pgwire, error-msgs

**Comment by refset** [comment] 2024-08-06 11:56
Ah thanks, have moved the example over.
