### ISSUE TITLE
Clarify nested list handling and errors

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3341] opened 2024-04-26 17:53 UTC
From @nivekuil ([thread](https://clojurians.slack.com/archives/CG3AM2F7V/p1714088717076619))

> Inserting complex lists (clojure code) gives an unexpected error

`{:xt/id 1 :data '(())}`

```
1. Unhandled java.lang.IllegalArgumentException
   Lists have one child Field. Found: none

        Preconditions.java:  205  org.apache.arrow.util.Preconditions/checkArgument
           ListVector.java:  116  org.apache.arrow.vector.complex.ListVector/initializeChildrenFromFields
                Field.java:  111  org.apache.arrow.vector.types.pojo.Field/createVector
```

**Comment by nivekuil** [comment] 2024-04-26 18:13
not just empty lists to be clear, `{:xt/id 1 :data '((1))}` gives the same error

**Comment by nivekuil** [comment] 2024-04-28 01:44
`{:xt/id 1 :data [[2] [1]]}` throws but `{:xt/id 1 :data [2 [1]]}` does not

**Comment by FiV0** [comment] 2024-04-30 08:02
@jarohen Currently when we are promoting the vectors we are only passing `FieldType` to update/promote any children. The problem is that list `Field`s (and by extension sets) need a child to initialize. Should we try to use `Field` instead? Just initializing with something canonical (like null list) might result in unwanted DUV's.

**Comment by FiV0** [comment] 2024-06-06 09:56
Likely fixed in the generative testing bash.

**Closed as completed by FiV0** 2024-06-06 09:56 UTC
Labels: sql

**Comment by refset** [comment] 2024-06-06 11:10
@FiV0 yep I just checked also against the examples above - all look good now :clap:
