### ISSUE TITLE
NPE while doing large `INSERT INTO ... RECORDS ..` with params

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3959] opened 2024-12-11 10:34 UTC
Ran into this while investing https://github.com/xtdb/xtdb/issues/3945.
The following 
```clj
(defn random-float [min max] (+ min (* (rand) (- max min))))

(defn docs
  [n]
  (->> (tu/->instants :minute 5 #inst "2020-01-01")
       (take (inc n))
       (partition 2 1)
       (map-indexed (fn [i [start end]]
                      {:_id i
                       :_valid_from start
                       :_valid_to end
                       :value (random-float -100 100)}))))

(defn ->param-str [n]
  (str (apply str (repeat (dec n) "?,")) "?"))

(deftest large-into-records-with-params
  (with-open [conn (jdbc-conn)]
    (let [batch (first (partition-all 1000 (docs 10000)))]
      (jdbc/execute! conn (into [(str "INSERT INTO readings RECORDS " (->param-str (count batch)))] (map xt-jdbc/->pg-obj) batch)))))
```
results `error: org.postgresql.util.PSQLException: ERROR: unexpected error on tx submit (report as a bug)`. 

The stacktrace on pg side is 
```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "x" is null
	at clojure.lang.Numbers.ops(Numbers.java:1099)
	at clojure.lang.Numbers.dec(Numbers.java:147)
	at xtdb.sql.plan.TableRowsVisitor$reify__34359.visitPostgresParameter(plan.clj:2073)
	at xtdb.antlr.Sql$PostgresParameterContext.accept(Sql.java:9187)
	at xtdb.sql.plan.TableRowsVisitor$reify__34359.visitParameterRecord(plan.clj:2070)
	at xtdb.antlr.Sql$ParameterRecordContext.accept(Sql.java:12236)
	at xtdb.sql.plan$accept_visitor.invokeStatic(plan.clj:41)
	at xtdb.sql.plan$accept_visitor.invoke(plan.clj:40)
	at clojure.core$partial$fn__5927.invoke(core.clj:2641)
	at clojure.core$map$fn__5950$fn__5951.invoke(core.clj:2759)
	at clojure.core.protocols$iterator_reduce_BANG_.invokeStatic(protocols.clj:42)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:52)
	at clojure.core.protocols$fn__8256.invokeStatic(protocols.clj:74)
	at clojure.core.protocols$fn__8256.invoke(protocols.clj:74)
	at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13)
	at clojure.core$transduce.invokeStatic(core.clj:7026)
	at clojure.core$into.invokeStatic(core.clj:7042)
	at clojure.core$into.invoke(core.clj:7029)
	at xtdb.sql.plan.TableRowsVisitor.visitRecordsValueList(plan.clj:2068)
	at xtdb.antlr.Sql$RecordsValueListContext.accept(Sql.java:12300)
	at xtdb.sql.plan.QueryPlanVisitor.visitRecordsValueList(plan.clj:2332)
	at xtdb.antlr.Sql$RecordsValueListContext.accept(Sql.java:12300)
	at xtdb.sql.plan.QueryPlanVisitor.visitRecordsValueConstructor(plan.clj:2328)
	at xtdb.antlr.Sql$RecordsValueConstructorContext.accept(Sql.java:12357)
	at xtdb.sql.plan.QueryPlanVisitor.visitInsertRecords(plan.clj:2344)
	at xtdb.antlr.Sql$InsertRecordsContext.accept(Sql.java:19349)
	at xtdb.sql.plan.StmtVisitor.visitInsertStatement(plan.clj:2564)
	at xtdb.antlr.Sql$InsertStatementContext.accept(Sql.java:19281)
	at xtdb.sql.plan.StmtVisitor.visitInsertStmt(plan.clj:2560)
	at xtdb.antlr.Sql$InsertStmtContext.accept(Sql.java:646)
	at xtdb.sql.plan$eval35084$fn__35086.invoke(plan.clj:2893)
	at xtdb.sql.plan$eval35060$fn__35061$G__35051__35068.invoke(plan.clj:2870)
	at xtdb.sql.plan$eval35080$fn__35081.invoke(plan.clj:2877)
	at xtdb.sql.plan$eval35060$fn__35061$G__35051__35068.invoke(plan.clj:2870)
	at xtdb.sql.plan$plan_statement.invokeStatic(plan.clj:2911)
	at xtdb.sql.plan$plan_statement.invoke(plan.clj:2909)
	at xtdb.sql$compile_query__39034.invoke(sql.clj:10)
	at xtdb.util$lru_memoize$fn__5035.invoke(util.clj:580)
	at xtdb.indexer$$reify__40319$fn__40320.invoke(indexer.clj:596)
	at xtdb.indexer$$reify__40319.indexOp(indexer.clj:594)
	at xtdb.indexer.Indexer$fn__40386$index_tx_ops__40391$fn__40406.invoke(indexer.clj:797)
	at clojure.lang.AFn.call(AFn.java:18)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
	at xtdb.indexer.Indexer$fn__40386$index_tx_ops__40391.invoke(indexer.clj:794)
	at xtdb.indexer.Indexer$fn__40386$fn__40414.invoke(indexer.clj:809)
	at xtdb.indexer.Indexer$fn__40386.invoke(indexer.clj:808)
	at xtdb.indexer.Indexer.indexTx(indexer.clj:767)
	at xtdb.log.watcher$watch_log_BANG_$reify__55209.accept(watcher.clj:49)
	at xtdb.log$tx_handler$fn__35197.invoke(log.clj:41)
	at clojure.core.protocols$iterator_reduce_BANG_.invokeStatic(protocols.clj:42)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:52)
	at clojure.core.protocols$fn__8256.invokeStatic(protocols.clj:74)
	at clojure.core.protocols$fn__8256.invoke(protocols.clj:74)
	at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6965)
	at clojure.core$reduce.invoke(core.clj:6947)
	at xtdb.log.NotifyingSubscriberHandler$fn__35230.invoke(log.clj:100)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by refset** [comment] 2024-12-11 10:36
Dupe of https://github.com/xtdb/xtdb/issues/3907 ? Should be fixed in `nightly` as of last night.

**Comment by jarohen** [comment] 2024-12-11 10:38
looks likely, yep.

@FiV0 also bear in mind the recommendation of `execute-batch!` in that card rather than `?, ?, ?, ?, ?, ...`

**Closed as not planned by jarohen** 2024-12-11 10:38 UTC
Labels: duplicate
